name:                swift-emmet
version:             0.1.0.0
github:              "YusukeHosonuma/swift-emmet"
license:             MIT
author:              "Yusuke Hosonuma"
maintainer:          "tobi462@gmail.com"
copyright:           "2021 Yusuke Hosonuma"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YusukeHosonuma/swift-emmet#README.md>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- text

library:
  source-dirs: src
  dependencies:
  - attoparsec
  - text

executables:
  swift-emmet:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - swift-emmet

tests:
  swift-emmet-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - swift-emmet
    - tasty
    - tasty-hunit
