name: PR

on: [pull_request]

jobs:
  test:
    runs-on: macos-latest # TODO: Linux イメージでもいいかも

    steps:
    - uses: actions/checkout@v2

    - name: Cache .stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: "stack-${{ hashFiles('**/stack.yaml.lock') }}"

    - uses: haskell/actions/setup@v1.2.0
      with:
        ghc-version: 8.10.4
        enable-stack: true
        stack-version: 'latest'

    - name: Install dependencies
      run: stack --system-ghc build --only-dependencies

    - name: Run tests
      run: stack --system-ghc test --local-bin-path=./bin
